name: Build Docker and Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Slurm version'
        required: true
        default: '23.11.8'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build --build-arg SLURM_VERSION=${{ github.event.inputs.version }} -t slurm_deb_builder .

      - name: Create output directory
        run: mkdir -p output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create my-app:latest)
          docker cp $container_id:/usr/src/slurm-smd*.deb ./output/
          docker cp $container_id:/usr/src/nccl/build/pkg/deb/*.deb ./output/
          ls -lah ./output/
          docker rm $container_id

#      - name: Upload Release Asset
#        uses: actions/upload-artifact@v3
#        with:
#          name: artifact
#          path: ./output/artifact
#
#      - name: Create GitHub Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v${{ github.event.inputs.version }}
#          release_name: Release ${{ github.event.inputs.version }}
#          draft: false
#          prerelease: false
#
#      - name: Upload Release Assets
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./output/artifact
#          asset_name: artifact
#          asset_content_type: application/octet-stream
